//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RememberBoxVF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientesexpo
    {
        public int id { get; set; }
        public string NombreNovio { get; set; }
        public string NombreNovia { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaBoda { get; set; }
        public string telefono1 { get; set; }
        public Nullable<int> cabina { get; set; }
        public Nullable<int> alfombra { get; set; }
        public Nullable<int> espejo { get; set; }
        public Nullable<int> tipies { get; set; }
        public Nullable<int> letras { get; set; }
        public Nullable<int> fotos { get; set; }
        public Nullable<double> precio_cabina { get; set; }
        public Nullable<double> precio_alfombra { get; set; }
        public Nullable<double> precio_espejo { get; set; }
        public Nullable<double> precio_tipies { get; set; }
        public Nullable<double> precio_letras { get; set; }
        public Nullable<double> precio_fotos { get; set; }
        public string observacion { get; set; }
        public string evento { get; set; }
        public Nullable<int> idEvento { get; set; }
    }
}
