//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RememberBoxVF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        public int Id_Contrato { get; set; }
        public string Nombre { get; set; }
        public string Jardin { get; set; }
        public Nullable<System.DateTime> FechaEv { get; set; }
        public Nullable<System.DateTime> FechaEm { get; set; }
        public string Servicios { get; set; }
        public int Precio { get; set; }
        public string FormaPago { get; set; }
    }
}
