//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RememberBoxVF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class jardin
    {
        public int Id_Jardin { get; set; }
        public string NomEnc { get; set; }
        public string NomJar { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    }
}
