//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RememberBoxVF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios
    {
        public int Id_servicio { get; set; }
        public string Servicio { get; set; }
        public int Precio { get; set; }
        public string Propiedades { get; set; }
    }
}
